development:
  adapter: postgresql
  encoding: unicode
  database: uhack_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: uhack_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: uhack_production
  pool: 5
