development:
  development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: amicibici_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: amicibici_production
  pool: 5
  username:
  password:
